# Generated by Django 2.2 on 2019-04-30 06:42

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber', models.BooleanField(default=False)),
                ('first_issue', models.IntegerField(blank=True, null=True, verbose_name='Premier numéro à envoyer')),
                ('subscription_date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Nom')),
                ('firstname', models.CharField(blank=True, max_length=20, null=True, verbose_name='Prénom')),
                ('company', models.CharField(blank=True, max_length=25, null=True, verbose_name='Société / Raison sociale')),
                ('region', models.CharField(choices=[('FRANCE', 'France'), ('SUISSE', 'Suisse'), ('AUTRE', 'Autre')], default='FRANCE', max_length=10, verbose_name='Région')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='Adresse*')),
                ('address_extra', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complément Adresse')),
                ('postal_code', models.CharField(max_length=10, null=True, verbose_name='Code postal')),
                ('postal_square', models.CharField(blank=True, max_length=10, null=True, verbose_name='Case postale (Suisse)')),
                ('city', models.CharField(max_length=50, null=True, verbose_name='Ville')),
                ('land', models.CharField(max_length=50, null=True, verbose_name='Pays')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone')),
                ('delivery_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Nom')),
                ('delivery_firstname', models.CharField(blank=True, max_length=20, null=True, verbose_name='Prénom')),
                ('delivery_company', models.CharField(blank=True, max_length=25, null=True, verbose_name='Société / Raison sociale')),
                ('delivery_region', models.CharField(choices=[('FRANCE', 'France'), ('SUISSE', 'Suisse'), ('AUTRE', 'Autre')], default='FRANCE', max_length=10, verbose_name='Région')),
                ('delivery_address', models.CharField(max_length=255, null=True, verbose_name='Adresse')),
                ('delivery_address_extra', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complément Adresse')),
                ('delivery_postal_code', models.CharField(max_length=10, null=True, verbose_name='Code postal')),
                ('delivery_postal_square', models.CharField(blank=True, max_length=10, null=True, verbose_name='Case postale (Suisse)')),
                ('delivery_city', models.CharField(max_length=50, null=True, verbose_name='Ville')),
                ('delivery_land', models.CharField(max_length=50, null=True, verbose_name='Pays')),
                ('delivery_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(blank=True, max_length=50, null=True, verbose_name='Thème')),
                ('number', models.IntegerField(unique=True, verbose_name='Numéro')),
                ('number_display', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Numéro affiché (optionnel)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='issues/', verbose_name='Image de couverture seule (608x644 px)')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='issues/', verbose_name='Miniature de couverture (230x377 px)')),
                ('date', models.CharField(max_length=50, verbose_name='Période')),
                ('price_eur', models.FloatField(default=22, verbose_name='Prix en euros')),
                ('price_sfranc', models.FloatField(default=25, verbose_name='Prix en francs suisses')),
                ('stock', models.IntegerField(default=1, verbose_name='Stock')),
                ('color', models.CharField(default='FFFFFF', max_length=6, verbose_name='Couleur (code hexadécimal)')),
                ('editorial', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Edito')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Sommaire')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30, verbose_name='Label du menu')),
                ('position', models.IntegerField(default='1')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texte simple ou colonne 1/2')),
                ('body_extra', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Colonne 2/2')),
                ('footer', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Mentions en bas de page')),
            ],
            options={
                'ordering': ['position', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.BooleanField(default=False)),
                ('shop', models.BooleanField(default=False)),
                ('next_issue', models.IntegerField(unique=True, verbose_name='Premier numéro pour abonnement')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('FRANCE', 'France'), ('SUISSE', 'Suisse'), ('AUTRE', 'Autre')], default='FRANCE', max_length=10, verbose_name='Région')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nom')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('number', models.IntegerField(default=4, verbose_name='Nombre de numéros')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Prix en euros')),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('CHF', 'Franc suisse'), ('USD', 'Dollar US')], default='EUROS', max_length=12, verbose_name='Devise')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, choices=[('ISSUE', 'issue'), ('SUBSC', 'subscription')], max_length=5, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Montant')),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('CHF', 'Franc suisse'), ('USD', 'Dollar US')], default='EUROS', max_length=12, verbose_name='Devise')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='magazine.Customer')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='magazine.Subscription')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='magazine.Subscription'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
