# Generated by Django 2.2 on 2019-05-13 09:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-number']},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['price']},
        ),
        migrations.AddField(
            model_name='customer',
            name='approval',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='extract',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Extrait'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_info',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Informations sur la commande'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='color',
            field=models.CharField(default='808C74', max_length=6, verbose_name='Couleur (code hexadécimal)'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='theme',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Thème'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='issues/', verbose_name='Miniature de couverture (230x377 px)'),
        ),
    ]
