# Generated by Django 2.2 on 2021-02-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_auto_20190513_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=50, null=True, verbose_name='Ville*'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='delivery_address',
            field=models.CharField(max_length=255, null=True, verbose_name='Adresse*'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='delivery_city',
            field=models.CharField(max_length=50, null=True, verbose_name='Ville*'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='delivery_land',
            field=models.CharField(max_length=50, null=True, verbose_name='Pays*'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='delivery_postal_code',
            field=models.CharField(max_length=10, null=True, verbose_name='Code postal*'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='delivery_postal_square',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Case postale'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='delivery_region',
            field=models.CharField(choices=[('FRANCE', 'France'), ('SUISSE', 'Suisse'), ('AUTRE', 'Autre')], default='FRANCE', max_length=10, verbose_name='Région*'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='land',
            field=models.CharField(max_length=50, null=True, verbose_name='Pays*'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(max_length=10, null=True, verbose_name='Code postal*'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postal_square',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Case postale'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='region',
            field=models.CharField(choices=[('FRANCE', 'France'), ('SUISSE', 'Suisse'), ('AUTRE', 'Autre')], default='FRANCE', max_length=10, verbose_name='Région*'),
        ),
    ]
