# Generated by Django 5.2.17 on 2026-08-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_auto_20210215_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='delivery_region',
            field=models.CharField(choices=[('FRANCE', 'France'), ('SUISSE', 'Suisse'), ('EUROPE', 'Europe'), ('AUTRE', 'Autre')], default='FRANCE', max_length=10, verbose_name='Région*'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='region',
            field=models.CharField(choices=[('FRANCE', 'France'), ('SUISSE', 'Suisse'), ('EUROPE', 'Europe'), ('AUTRE', 'Autre')], default='FRANCE', max_length=10, verbose_name='Région*'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='region',
            field=models.CharField(choices=[('FRANCE', 'France'), ('SUISSE', 'Suisse'), ('EUROPE', 'Europe'), ('AUTRE', 'Autre')], default='FRANCE', max_length=10, verbose_name='Région'),
        ),
    ]
